name: Deploy App to GitHub Pages and Render

on:
  push:
    branches:
      - main  # or 'master' based on your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # or your desired Node.js version

      # Install dependencies and build the Vite app
      - name: Install dependencies
        run: |
          cd frontend
          npm install
          npm run build

      # Set up Python for the backend
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # or your desired Python version

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      # Deploy to GitHub Pages using gh-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to
          folder: frontend/dist  # The folder containing the production build

      # Deploy the project to Render
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_PAT }}
          wait_deploy: true
