name: Flask + Vite App Docker Image

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_TOKEN

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: DOCKERFILE
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/contact-book-fullstack:latest

